name: Fix Go projects
description: Fix Go projects
inputs:
  files:
    required: false
    description: space separated file paths to be formatted
  aqua_version:
    required: true
    description: The version of aqua
runs:
  using: composite
  steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        persist-credentials: false
    - run: echo "AQUA_GLOBAL_CONFIG=${AQUA_GLOBAL_CONFIG:-}:${GITHUB_ACTION_PATH}/aqua/aqua.yaml" >> "$GITHUB_ENV"
      shell: bash
    - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
      with:
        aqua_version: ${{inputs.aqua_version}}
        aqua_opts: -l -a

    # aqua-checksums.json
    - run: aqua upc -prune
      shell: bash
      env:
        AQUA_GITHUB_TOKEN: ${{github.token}}

    # Newlines
    - run: nllint -v
      shell: bash
      env:
        AQUA_GITHUB_TOKEN: ${{github.token}}
    - run: git ls-files | xargs nllint -f -s
      shell: bash

    # go mod tidy
    - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
      with:
        go-version-file: go.mod
    - run: go mod tidy
      shell: bash

    # golangci-lint
    - run: golangci-lint version
      shell: bash
      env:
        AQUA_GITHUB_TOKEN: ${{github.token}}
    - run: golangci-lint fmt
      shell: bash

    # Generate JSON Schema
    - shell: bash
      run: |
        if [ -f cmd/gen-jsonschema/main.go ]; then
          go run ./cmd/gen-jsonschema
        fi

    # Generate USAGE
    - shell: bash
      run: |
        if [ -f scripts/generate-usage.sh ]; then
          bash scripts/generate-usage.sh
        fi

    - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27 # v1.3.2
