name: Fix Go projects
description: Fix Go projects
inputs:
  files:
    required: false
    description: space separated file paths to be formatted
  aqua_version:
    required: true
    description: The version of aqua
runs:
  using: composite
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - run: echo "AQUA_GLOBAL_CONFIG=${AQUA_GLOBAL_CONFIG:-}:${GITHUB_ACTION_PATH}/aqua/aqua.yaml" >> "$GITHUB_ENV"
      shell: bash
    - uses: aquaproj/aqua-installer@e2d0136abcf70b7a2f6f505720640750557c4b33 # v3.1.1
      with:
        aqua_version: ${{inputs.aqua_version}}
        aqua_opts: -l -a

    # aqua-checksums.json
    - run: aqua upc -prune
      shell: bash

    # Newlines
    - run: git ls-files | xargs nllint -f -s
      shell: bash

    # go mod tidy
    - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
      with:
        go-version-file: go.mod
    - run: go mod tidy
      shell: bash

    # gofumpt
    - run: gofumpt -version
      shell: bash
    - shell: bash
      run: |
        if [ -n "${FILES:-}" ]; then
          # shellcheck disable=SC2086
          gofumpt -l -w $FILES
          exit 0
        fi
        git ls-files | grep -E "\.go$" | xargs gofumpt -l -w
      env:
        FILES: ${{ inputs.files }}

    - uses: autofix-ci/action@2891949f3779a1cafafae1523058501de3d4e944 # v1.3.1
