name: Fix Go projects
description: Fix Go projects
inputs:
  files:
    required: false
    description: space separated file paths to be formatted
  aqua_version:
    required: true
    description: The version of aqua
runs:
  using: composite
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        persist-credentials: false
    - run: echo "AQUA_GLOBAL_CONFIG=${AQUA_GLOBAL_CONFIG:-}:${GITHUB_ACTION_PATH}/aqua/aqua.yaml" >> "$GITHUB_ENV"
      shell: bash
    - uses: aquaproj/aqua-installer@5e54e5cee8a95ee2ce7c04cb993da6dfad13e59c # v3.1.2
      with:
        aqua_version: ${{inputs.aqua_version}}
        aqua_opts: -l -a

    # aqua-checksums.json
    - run: aqua upc -prune
      shell: bash

    # Newlines
    - run: git ls-files | xargs nllint -f -s
      shell: bash

    # go mod tidy
    - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      with:
        go-version-file: go.mod
    - run: go mod tidy
      shell: bash

    # gofumpt
    - run: gofumpt -version
      shell: bash
    - shell: bash
      run: |
        if [ -n "${FILES:-}" ]; then
          # shellcheck disable=SC2086
          gofumpt -l -w $FILES
          exit 0
        fi
        git ls-files | grep -E "\.go$" | xargs gofumpt -l -w
      env:
        FILES: ${{ inputs.files }}

    # Generate JSON Schema
    - shell: bash
      run: |
        if [ -f cmd/gen-jsonschema/main.go ]; then
          go run ./cmd/gen-jsonschema
        fi

    # Generate USAGE
    - shell: bash
      run: |
        if [ -f scripts/generate-usage.sh ]; then
          bash scripts/generate-usage.sh
        fi

    - uses: suzuki-shunsuke/autofixci-action@989fe99ca39af1980b3515837570511eea7c6285 # v1.3.2-2
