name: Fix Go projects
description: Fix Go projects
inputs:
  files:
    required: false
    description: space separated file paths to be formatted
  aqua_version:
    required: true
    description: The version of aqua
  takumi_guard_bot_id:
    required: false
    description: Takumi Guard bot ID. This requires the permission `id-token:write`.
runs:
  using: composite
  steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        persist-credentials: false
    - run: echo "AQUA_GLOBAL_CONFIG=${AQUA_GLOBAL_CONFIG:-}:${GITHUB_ACTION_PATH}/aqua/aqua.yaml" >> "$GITHUB_ENV"
      shell: bash
    - uses: aquaproj/aqua-installer@96a9bc20066c5bf5e275b41019cfc165b25f4e2e # v4.0.5
      with:
        aqua_version: ${{inputs.aqua_version}}
        aqua_opts: -l -a

    # aqua-checksums.json
    - run: aqua upc -prune
      shell: bash
      env:
        AQUA_GITHUB_TOKEN: ${{github.token}}

    # Newlines
    - run: nllint -v
      shell: bash
      env:
        AQUA_GITHUB_TOKEN: ${{github.token}}
    - run: git ls-files | xargs nllint -f -s
      shell: bash

    # go mod tidy
    - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
      with:
        go-version-file: go.mod

    - uses: flatt-security/setup-takumi-guard-golang@2e3c7c40b538cd68b2ac483def12982ebc8bc02e # v1
      with:
        bot-id: ${{inputs.takumi_guard_bot_id}}

    - run: go mod tidy
      shell: bash

    # golangci-lint
    - run: golangci-lint version
      shell: bash
      env:
        AQUA_GITHUB_TOKEN: ${{github.token}}
    - run: golangci-lint fmt
      shell: bash

    # Generate JSON Schema
    - shell: bash
      run: |
        if [ -f cmd/gen-jsonschema/main.go ]; then
          go run ./cmd/gen-jsonschema
        fi

    # Generate USAGE
    - shell: bash
      env:
        AQUA_GITHUB_TOKEN: ${{github.token}}
      run: |
        if [ -f scripts/generate-usage.sh ]; then
          bash scripts/generate-usage.sh
        fi

    - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1.3.4
